spring.application.name=inscripcion-cursos

# Oracle Autonomous Database
spring.datasource.url=jdbc:oracle:thin:@inscripciondb_high?TNS_ADMIN=${TNS_ADMIN:C:/Wallet_INSCRIPCIONDB}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=ADMIN
spring.datasource.password=InscripcionDuoc.1

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# AWS S3
aws.region=us-east-1
aws.s3.bucket=mibucketduoc1410

# Servidor
server.port=8081

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://wiladuoc1.b2clogin.com/e99677de-5bd9-40e9-acfb-80acb38a38cb/v2.0/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://wiladuoc1.b2clogin.com/wiladuoc1.onmicrosoft.com/B2C_1_inscripcion_v2/discovery/v2.0/keys
spring.security.oauth2.resourceserver.jwt.audiences=449048c5-bb65-40f1-9f56-3cbc9f2d5bea