name: CI-CD EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Dar permisos a Maven Wrapper
        run: chmod +x mvnw

      - name: Compilar aplicación
        run: ./mvnw clean package -DskipTests

      - name: Verificar construcción Docker
        run: docker build -t inscripcion-cursos:latest .

      - name: Desplegar en Amazon EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/inscripcion-cursos-2
            git fetch origin main
            git reset --hard origin/main
            docker compose up -d --build
            docker ps
